### PR TITLE
Login/Logout UI fixes

### PR DESCRIPTION
**Pull request by kohchihao**
In this PR,
- `User` can finally `/logout`
- There is a new login screen. 😱
- Only after signup/login, the UI will automatically change to display `loggedInPanel` which is the main UI
- Fixed all test.

### CODE REVIEW

**Comment by juxd** [comment]
Should executing commands that require login when user isn't logged in raise an exception instead? 🤔

**Comment by juxd** [comment]
Should we raise an exception on 'unauthorised' commands?

**Comment by juxd** [comment]
Should we raise an exception on 'unauthorised' commands?

**Comment by juxd** [comment]
Should we raise an exception on 'unauthorised' commands?

**Comment by juxd** [comment]
Should we raise an exception on 'unauthorised' commands?

**Comment by juxd** [comment]
Should we raise an exception on 'unauthorised' commands?

**Comment by kohchihao** [comment]
hi

**Pull request merged**
